### PR TITLE
146: Investigate missing avatar issue

### LINKED ISSUE #146: Contributing author avatar issue
If an author doesn't have a profile picture, it is replaced by a placeholder. However, for articles with multiple contributors, if any of the contributing authors lack a profile picture it renders as a broken link.

### PR DESCRIPTION
**Pull request by dogle-scottlogic**
Fix for broken avatar link when a contributor has no image. Addresses issue #146

### CODE REVIEW

**Comment by chriswilty** [comment]
Do we have an example, e.g. before/after screenshots or a link to a broken article?

**Comment by dogle-scottlogic** [comment]
> Do we have an example, e.g. before/after screenshots or a link to a broken article?

😢 - never thought to take a screen shot like a muppet! I think I have something on a branch - let me look

**Comment by dogle-scottlogic** [comment]
Before:
before

After:
after

After (with image):
after-pic

**Review by chriswilty — APPROVED** [review]
Nice work 👌

**Pull request merged**
